-- Insert statements for vehicle_brands table
INSERT INTO `vehicle_brands` (`name`, `created_at`, `updated_at`, `is_active`, `is_deleted`, `CreatedAt`, `UpdatedAt`, `IsActive`, `IsDeleted`) VALUES
-- Yerli Markalar
('TOGG', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Anadol', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Devrim', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),

-- Yabancı Markalar
('Abarth', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Acura', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Alfa Romeo', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Aston Martin', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Audi', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Bentley', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('BMW', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Brilliance', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Bugatti', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('BYD', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Cadillac', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Changan', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Chery', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Chevrolet', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Chrysler', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Citroën', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Cupra', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Dacia', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Daihatsu', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Dodge', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('DS Automobiles', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Ferrari', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Fiat', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Ford', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Geely', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Genesis', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Great Wall', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Haval', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Honda', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Hummer', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Hyundai', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Infiniti', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('JAC', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Jaguar', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Jeep', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Kia', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Lada', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Lamborghini', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Land Rover', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Lexus', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Lincoln', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Lotus', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Maserati', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Maxus', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Mazda', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('McLaren', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Mercedes-Benz', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('MG', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Mini', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Mitsubishi', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Nissan', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Opel', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Peugeot', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Polestar', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Porsche', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Proton', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Renault', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Rolls-Royce', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Seat', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Skoda', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Smart', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('SsangYong', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Subaru', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Suzuki', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('TATA', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Tesla', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Toyota', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Volkswagen', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Volvo', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Wuling', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),

-- Ticari Araç Markaları
('BMC', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('DAF', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Fiat Professional', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Ford Trucks', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Hino', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Iveco', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Isuzu', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Karsan', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('MAN', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Mercedes-Benz Trucks', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Mitsubishi Fuso', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Otokar', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Scania', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Temsa', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Volvo Trucks', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),

-- Motosiklet Markaları
('Aprilia', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Benelli', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('BMW Motorrad', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Ducati', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Harley-Davidson', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Honda', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Kawasaki', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('KTM', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Moto Guzzi', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('MV Agusta', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Royal Enfield', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Suzuki', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Triumph', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Vespa', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Yamaha', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),

-- ATV/UTV Markaları
('Arctic Cat', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Can-Am', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('CFMOTO', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Honda', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Kawasaki', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Polaris', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Suzuki', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'),
('Yamaha', NOW(), NOW(), 1, 0, NOW(), NOW(), b'1', b'0'); 